---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit:
  - Пользователь должен иметь возможность переключаться между страницами товаров
  - Пользователь должен иметь возможность переключать язык сайта
  - Пользователь должен иметь возможность удалить товары из корзины
  - Перевод валюты из долларов в рубли при переключении языка на русский
  - Нужно реализовать возможность регистрации

